import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { LiffProvider } from "@/components/layouts/LiffProvider";
import { ThemeProvider } from "@/components/layouts/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";

import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";

import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";

export const metadata: Metadata = {
	title: "くそぬきbot",
	description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });
config.autoAddCss = false;

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="ja">
			<head>
				{/* 一般 */}
				<link rel="manifest" href="/manifest.json" />
				<meta name="theme-color" content="#b8e986" />
				<link rel="icon" sizes="192x192" href="/icon-192x192.png" />
				<link rel="icon" href="/favicon.ico" />

				{/* safari */}
				<meta name="apple-mobile-web-app-capable" content="yes" />
				<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
				<meta name="apple-mobile-web-app-title" content="くそぬきbot" />
				<link rel="apple-touch-icon" sizes="192x192" href="/icon-192x192.png" />
			</head>
			<body className={inter.className}>
				<SpeedInsights />
				<Analytics />
				<LiffProvider liffId={process.env.NEXT_PUBLIC_LIFF_ID || ""}>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<div className="flex flex-col justify-between w-full h-full min-h-screen">
							<Header />
							<main className="flex-auto w-full max-w-3xl px-4 py-4 mx-auto sm:px-6 md:px-6 md:py-6">
								{children}
							</main>
							<Toaster />
							<Footer />
						</div>
					</ThemeProvider>
				</LiffProvider>
			</body>
		</html>
	);
}
