import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { LiffProvider } from "@/components/layouts/LiffProvider";

import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";

export const metadata: Metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });
config.autoAddCss = false;

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="ja">
			<body className={inter.className}>
				<LiffProvider liffId={process.env.NEXT_PUBLIC_LIFF_ID || ""}>
					<div className="flex flex-col justify-between w-full h-full min-h-screen">
						<Header />
						<main className="flex-auto w-full max-w-3xl px-4 py-4 mx-auto sm:px-6 md:px-6 md:py-6">
							{children}
						</main>
						<Footer />
					</div>
				</LiffProvider>
			</body>
		</html>
	);
}
